### ISSUE TITLE
Refactor Participant Model

### ISSUE THREAD

**Issue by c5f** [c5f/beemo#2]
- [x] Rename existing `Participant` ~~and `RParticipant`~~ to `InterventionParticipant` ~~and `RInterventionParticipant` respectively~~.
- [x] Refactor `update_participants` in `sync.models` to call a helper method named `update_intervention_participants` containing the existing logic.
- [x] Create a new abstract Django model named `Participant` to hold any common data and logic between Control and Intervention schemas.
  - [x] Setup [generic relations](https://docs.djangoproject.com/en/1.5/ref/contrib/contenttypes/#generic-relations) with `generic.GenericForeignKey` for:
    - [x] `Call.participant`
    - [x] `Email.participant`
    - [x] `ParticipantProblem.participant`  (rename class from `InterventionParticipantProblem`)
  - [x] Setup [reverse generic relations](https://docs.djangoproject.com/en/1.5/ref/contrib/contenttypes/#reverse-generic-relations) with `generic.GenericRelation` for:
    - [x] `Participant.calls`
    - [x] `Participant.emails`
    - [x] `Participant.participant_problems`
- [x] Refactor `app.management.commands` methods `update_touches` and `update_adherence` to work with the new structure.

**Comment by colinsf** [comment]
Files containing `Participant`:

```
beemo/api/serializers.py
beemo/api/views.py
beemo/app/management/commands/update_adherence.py
beemo/app/management/commands/update_touches.py
beemo/app/models.py
beemo/app/tests/model_util_tests.py
beemo/app/tests/participant_tests.py
beemo/sync/models.py
```

Files containing `RParticipant`:

```
beemo/sync/models.py
```

**Comment by colinsf** [comment]
Refactored `RParticipant` in a feature branch since it only affected one file.

Also refactored the call to `update_participants` to use a storefront for control and intervention updates.

**Comment by c5f** [comment]
For adding generic `ForeignKey` relationships, consult the [Django docs](https://docs.djangoproject.com/en/1.5/ref/contrib/contenttypes/#generic-relations).
